apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-digma-measurement-analysis-deployment
  labels:
    app: digma-measurement-analysis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digma-measurement-analysis
  template:
    metadata:
      labels:
        app: digma-measurement-analysis
    spec:
      containers:
      - name: digma-measurement-analysis
        image: digmatic/digma-measurement-analysis:{{ .Chart.AppVersion }}
        env:
        {{- include "env.digmaEnv" . | nindent  8 }}
        {{- include "env.digmaSite" . | nindent  8 }}
        {{- include "env.redis" . | nindent  8 }}
        {{- include "env.influx" . | nindent  8 }}
        {{- include "env.rabbit" . | nindent  8 }}
        {{- include "env.otlpExporter" . | nindent  8 }}
        - name: OtlpSamplerProbability
          value: {{ .Values.digmaSelfDiagnosis.otlpSamplerProbability| quote}}
