apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-rabbitmq-stateful-set
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: {{ tpl .Values.rabbitMq.host . }}
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: rabbitmq
        image: rabbitmq:{{ .Values.rabbitMq.imageTag }}
        resources:
          requests:
            memory: {{ .Values.rabbitMq.resources.requests.memory }}
            cpu: {{ .Values.rabbitMq.resources.requests.cpu }}
          limits:
            memory: {{ .Values.rabbitMq.resources.limits.memory }}
            cpu: {{ .Values.rabbitMq.resources.limits.cpu }}
        ports:
          - containerPort: 5672
          - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitMq.username}}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbitMq.password}}
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq/
        - name: rabbitmq-data
          mountPath: /var/log/rabbitmq/
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  # persistentVolumeClaimRetentionPolicy:
  #   whenDeleted: Retain
