debug: true

redis:
  host: "{{ .Release.Name }}-redis"

influx:
  host: "{{ .Release.Name }}-influxdb"

postgres:
  host: "{{ .Release.Name }}-postgres"
  port: 5432
  username: postgres
  password: postgres

rabbit:
  host: "{{ .Release.Name }}-rabbitmq"
  username: admin
  password: admin

pgadmin:
  email: admin@admin.com
  password: admin

elasticApmServer:
  host: "{{ .Release.Name }}-apm"

digmaCollectorApi:
  host: "{{ .Release.Name }}-collector-api"

digmaBackendApi:
  host: "{{ .Release.Name }}-collector-backend"

digmaAnalytics:
  host: "{{ .Release.Name }}-analytics"