kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-digma-plugin-api-service-lb
spec:
  type: LoadBalancer
  selector:
     app: "digma-plugin-api"
  ports:
    - name: plugin-api
      protocol: TCP
      port: 5051
