apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.postgres.host . }}
spec:
  selector:
    app/postgres: ""
  ports:
  - port: {{ .Values.postgres.port }}
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.redis.host . }}
spec:
  selector:
    app/redis: ""
  ports:
  - port: 6379
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.rabbit.host . }}
spec:
  selector:
    app/rabbitmq: ""
  ports:
  - port: 5672
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.influx.host . }}
spec:
  selector:
    app/influxdb: ""
  ports:
  - port: 8086
    protocol: TCP
    
---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.digmaAnalytics.host . }}
spec:
  selector:
    app/digma-analytics: ""   
  ports:
  - port: 5052
    protocol: TCP 

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.digmaCollectorApi.host . }}
spec:
  selector:
     app/digma-collector-api: ""
  ports:
    - name: http
      protocol: TCP
      port: 5049
    - name: grpc
      protocol: TCP
      port: 5050

    
{{ if .Values.debug }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.elasticApmServer.host . }}
spec:
  selector:
    app/elastic-apm-server: ""
  ports:
  - port: 4317
    protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-debug-clients
spec:
  selector:
     app/all-debug: ""
  ports:

    - name: kibana
      protocol: TCP
      port: 81
      targetPort: 5601

    - name: redis-commander
      protocol: TCP
      port: 82
      targetPort: 8081

    - name: pgadmin
      protocol: TCP
      port: 83
      targetPort: 8080


{{ end }}