{{- if not .Values.traefik }}

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service-lb
spec:
  type: LoadBalancer
  selector:
     app: sample-app-go
  ports:
  - protocol: TCP
    port: 8011

{{- else -}}

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service-cip
spec:
  selector:
     app: sample-app-go
  ports:
  - protocol: TCP
    port: 8011

--- 

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-traefik-route
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Path(`/go`) 
    services:
    - kind: Service
      name: {{ .Release.Name }}-service-cip
      port: 8011
      # scheme: https

{{- end -}}