apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: digma-plugin-api-ingress-route
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`digma`)
    services:
    - kind: Service
      name: digma-plugin-api # [2] The digma's plugin api service name
      port: 5051
      scheme: http

# ---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: digma-plugin-api-ingress
# spec:
#   rules:
#   - host: "digma"
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: digma-plugin-api
#             port:
#               number: 5051
